language: ruby
rvm:
  - 2.1.3
before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - manuel.vidaurre@agiltec.com.mx
branches:
  only:
    - master
